id: AA4E9CCAA
title: Toh_196-The_Dwelling_Place_of_Manjusri-v2
type: translation
pechas:
- I5A62F1CA
- IBBC734E4
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-061-016
  eft-text-version: 1.1.5 2020
  title: Toh_196-The_Dwelling_Place_of_Manjusri-v2
alignment_to_base:
  I5A62F1CA/749C: 0F6F
  IBBC734E4/DDEF: 0F6F
